rtmpdump: Switch to using GNU TLS instead of openssl10
Source: meta-openembedded
MR: '00000'
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 4cd3a39f22a2712bfa8fc657d09fe2c7765a4005
Description:

Signed-off-by: Khem Raj <raj.khem@gmail.com>
[THUD: fixes usr/include/openssl/rc4.h:74:5: error: unknown type name 'RC4_INT']
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>