xterm: Remove undeclared variables introduced by backport
Source: meta-openembedded
MR: 124034, 125003
Type: Security Fix
Disposition: Merged from meta-openembedded
ChangeID: 7ae42df58f2bcc730153715c3339a6875b0b2497
Description:

CVE-2022-45063 ported onto the dunfell baseline introduces two
variables that cause xterm to fail compilation with the error

./fontutils.c:4143:13: error: 'added' undeclared (first use in this function)

These two variables don't appear to be defined at all in findXftGlyph for
xterm_353, so they should be removed.

Fixes: 10148c538ebc("xterm : Fix CVE-2022-45063 code execution via OSC 50 input sequences] CVE-2022-45063")
Signed-off-by: Chris Rogers <crogers122@gmail.com>
Tested-by: Jason Andryuk <jandryuk@gmail.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>