gnome-keyring: upgrade 46.1 -> 46.2
Source: meta-openembedded
MR: 302820
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 01f91cef8da8063b6559305dd54ea6808bd6c0d2
Description:

Changelog:
=========
* Don't use 'bool' as variable name
* autogoo: replace AC_HELP_STRING with AS_HELP_STRING
* Default "automatically unlock" checkbox to false
* build: Fix distcheck with systemd unit
* rpc-layer: Fix undefined reference to g_strlcpy
* Updated translations

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 0e55ce901a9697f273b1b04dc6daa15b81d4173f)
Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Anuj Mittal <anuj.mittal@oss.qualcomm.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>