python3-django: Fix undefined _lazy_re_compile
Source: meta-openembedded
MR: 302734
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: bca6ddaa0d791bd2a95bf72edca3bb70b03e8cce
Description:

Fix the following error introduced by CVE-2024-27351.patch and
CVE-2025-32873.patch:

NameError: name '_lazy_re_compile' is not defined

Signed-off-by: Haixiao Yan <haixiao.yan.cn@windriver.com>
Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>