krb5: fix build with gcc-15
Source: meta-openembedded
MR: 395209
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: acbcafe3f5ea8e271562d3f79bf511ff60248d44
Description:

* fixes:
  http://errors.yoctoproject.org/Errors/Details/848727/

ss_internal.h:88:6: error: conflicting types for 'ss_delete_info_dir'; have 'void(void)'
   88 | void ss_delete_info_dir();
      |      ^~~~~~~~~~~~~~~~~~
...

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit f26536c2f6f0617610fca95e5bb6953e843f9288)
Signed-off-by: Anuj Mittal <anuj.mittal@oss.qualcomm.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>