python3-pillow: add tk to RDEPENDS ptest pkg only if x11 in DISTRO_FEATURES
Source: meta-openembedded
MR: 124675
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: d413a66d2034134cddf78d9ee611f7ab3cba70da
Description:

commit 7b0e71e00 ("python3-pillow: add ptest support", 2023-01-31)
added tk to RDEPENDS:${PN}-ptest. Which cause this error on non x11
builds:

    ERROR: Nothing RPROVIDES 'tk' (but meta-openembedded/meta-python/recipes-devtools/python/python3-pillow_9.4.0.bb
           RDEPENDS on or otherwise requires it) tk was skipped: missing required
           distro feature 'x11' (not in DISTRO_FEATURES)
    NOTE: Runtime target 'tk' is unbuildable, removing...
          Missing or unbuildable dependency chain was: ['tk']
    NOTE: Runtime target 'iotmanager' is unbuildable, removing...
          Missing or unbuildable dependency chain was: ['iotmanager', 'python3-pillow', 'tk']
    ERROR: Required build target 'update-runtime' has no buildable providers.
           Missing or unbuildable dependency chain was:
           ['update-runtime', 'runtime-image', 'iotmanager', 'python3-pillow', 'tk']

Add tk dependency only if DISTRO_FEATURES includes x11

(cherry picked from commit 6e8c90560e0aa8fe2ebfb791985cb75fd7490527)
Signed-off-by: Geoff Parker <geoffrey.parker@arthrex.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>