ckermit: Define return type for main
Source: meta-openembedded
MR: 296370
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 8e135096102ca2ce0ee64f42b88268b2ef5c10aa
Description:

Newer compilers e.g. clang19+ will treat implicit function prototypes
as errors, therefore define main() with a valid return type

Fixes
ckwart.c:531:1: error: return type defaults to ‘int’ [-Wimplicit-int]
  531 | main(argc,argv) int argc; char **argv; {
      | ^~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 9813fb56d22acad36d70158335b8ee9f4a05ad89)
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>