network-manager-applet: add opengl to REQUIRED_DISTRO_FEATURES
Source: meta-openembedded
MR: 297304
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 9f1f1dfcdbd616f2368814ae1b60dc307e7bc437
Description:

Fixes:
  ERROR: Nothing PROVIDES 'libnma' (but /build/layers/meta-openembedded/meta-gnome/recipes-connectivity/network-manager-applet/network-manager-applet_1.26.0.bb DEPENDS on or otherwise requires it)
  libnma was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'network-manager-applet', 'libnma']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 9f8799d59471459fa1d79a001c999c47503701d5)
Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>