libgweather4: Upgrade to 4.4.4
Source: meta-openembedded
MR: 302820
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 4808353b953401165df1d9b19534b5f3e363d090
Description:

- Fix deprecation warnings [!300]
- Fix introspection annotation for async functions [!318]
- Plug some memory leaks [!321]
- Translation updates

Use GI_TYPELIB_PATH to point to typlib paths in target sysroot

Fixes
| FAILED: data/Locations.bin
| /mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/libgweather4/4.4.4/libgweather-4.4.4/build-aux/meson/gen_locations_variant.py ../libgweather-4.4.4/data/Locations.xml data/Locations.bin
| Traceback (most recent call last):
|   File "/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/libgweather4/4.4.4/libgweather-4.4.4/build-aux/meson/gen_locations_variant.py", line 7, in <module>
|     from gi.repository import GLib
|   File "/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/libgweather4/4.4.4/recipe-sysroot-native/usr/lib/python3.13/site-packages/gi/importer.py", line 133, in create_module
|     raise ImportError('cannot import name %s, '
|                       'introspection typelib not found' % namespace)
| ImportError: cannot import name GLib, introspection typelib not found

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Cc: Andreas Müller <schnitzeltony@gmail.com>
(cherry picked from commit 054716edca0ed56c171b5cb8d375c6bdf53eaa4b)
Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Anuj Mittal <anuj.mittal@oss.qualcomm.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>