libnma: add opengl to REQUIRED_DISTRO_FEATURES
Source: meta-openembedded
MR: 297304
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: d26055629736d94cc6846a21dc4360ddaf6db1aa
Description:

libnma depends on gtk4 which needs opengl DISTRO_FEATURES enabled.

Fixes:
  ERROR: Nothing PROVIDES 'gtk4' (but /build/layers/meta-openembedded/meta-gnome/recipes-connectivity/libnma/libnma_1.8.38.bb DEPENDS on or otherwise requires it)
  gtk4 was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'network-manager-applet', 'libnma', 'gtk4']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit a3eafe3698c9178d906f2e570e675999f941d395)
Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>