freeglut: return x11 to REQUIRED_DISTRO_FEATURES
Source: meta-openembedded
MR: 368607
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 47bcf0d9df8be47453e3a95e04e97da19c1885a3
Description:

* depends on libxi causing:
ERROR: Nothing PROVIDES 'libxi' (but /OE/build/luneos-nanbield/meta-openembedded/meta-oe/recipes-graphics/freeglut/freeglut_3.4.0.bb DEPENDS on or otherwise requires it)
libxi was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'freeglut', 'libxi']

for distros with opengl but without x11 in DISTRO_FEATURES

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>