packagegroup-meta-multimedia: Remove library only packages from rdeps
Source: meta-openembedded
MR: 170728
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 66ec16850573a7ec69248b81f9904cdfba79b930
Description:

Because they get renamed, it is better to ignore them and let a
dependency build them

Fixes errors like
ERROR: packagegroup-meta-multimedia-1.0-r0 do_package_write_ipk: An allarch packagegroup shouldn't depend on packages which are dynamically renamed (gssdp to libgssdp-1.2-0)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit eafecde2aedae38879b4c45dd213ff9483f209ad)
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>