dstat: Add missing python-six runtime dependency
Source: meta-openembedded
MR: 112422
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 5368c7c63d0703ba9e2b64307d97778481038ccd
Description:

The tool depends on the six module, add it, otherwise the following
traceback happens when running it on the target:

Traceback (most recent call last):
  File "/usr/bin/dstat", line 32, in <module>
    import six
ModuleNotFoundError: No module named 'six'

Signed-off-by: Marek Vasut <marex@denx.de>
Cc: Khem Raj <raj.khem@gmail.com>
Cc: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>