nodejs: Fix arm32/thumb builds with clang
Source: meta-openembedded
MR: 108246
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 00cf8917dc2a3c76ab7ec73a82c00ff079ddddbc
Description:

Backport a patch from upstream to take care of build failure e.g.

| ../deps/v8/src/codegen/arm/cpu-arm.cc:38:16: error: write to reserved register 'R7'
|   asm volatile("svc 0\n"
|                ^
| 1 error generated.

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 45a2dfdd0f16ed6941926e2dca1ad90f36e120bc)
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>