geoip: fix do_fetch error
Source: meta-openembedded
MR: 296370
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 371879bee73e7b69ebc704257094359be8d339b5
Description:

Change the SRC_URI to the correct value due to the following error:
ERROR: geoip-1.6.12-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'http://sources.openembedded.org/GeoIP.dat.20181205.gz;apply=no;name=GeoIP-dat;')

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit aadc2ac9dc49dfb5a2066401f22e7b553b324313)
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>