python3-django: Fix missing JSONField in django.db.models
Source: meta-openembedded
MR: 302734
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: c1d50d3e50c1348e75187c4cfd71e05b3a4ccdef
Description:

Fix the following error introduced by CVE-2024-42005.patch:

AttributeError: module 'django.db.models' has no attribute 'JSONField'

The patch assumes JSONField is available from django.db.models, which
is not the case for this Django version.

Revert the changes in the following files to restore compatibility:
tests/expressions/models.py
tests/expressions/test_queryset_values.py

Signed-off-by: Haixiao Yan <haixiao.yan.cn@windriver.com>
Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>