sysprof: Enable sysprofd/libsysprof only when polkit in DISTRO_FEATURES
Source: meta-openembedded
MR: 112422
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 13ceac25a8b55f367ce849900e66a184a6001e9d
Description:

This change is cherry-picked from upstream/master.

It fixes yocto-check-layer error:

ERROR: Nothing PROVIDES 'polkit' (but /home/builder/src/base/meta-openembedded/meta-gnome/recipes-kernel/sysprof/sysprof_3.34.1.bb DEPENDS on or otherwise requires it)
polkit was skipped: missing required distro feature 'polkit' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Cc: Andreas Müller <schnitzeltony@gmail.com>
Signed-off-by: akash hadke <akash.hadke@kpit.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>