crash: add zlib-native to depends for crash-cross
Source: meta-openembedded
MR: 302820
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 7e74032909d728d8a70b7e1c9a0c3b2b2f865ca3
Description:

Fix the following error when using buildtools-extended:

va_server.c:20:10: fatal error: zlib.h: No such file or directory
   20 | #include <zlib.h>
      |          ^~~~~~~~

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit bd745115de76de7242e3e7e69b29f1ae507fea13)
Signed-off-by: Anuj Mittal <anuj.mittal@oss.qualcomm.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>