python-evdev: Use target header to generate ecodes.c
Source: meta-openembedded
MR: 95432
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: d23612ff10eb6f43cd8e13d4c03fe8d9d38898fd
Description:

ecodes.c is generated file and if we do not specify the
linux input headers it happiliy defaults to /usr/include/
to look for these headers while emitting code for ecodes.c
which can cause gripes when build systems kernel UAPI is
different than the target kernel. Mysterious build errors
or even worse runtime errors can start to appear.

e.g.

| evdev/ecodes.c:603:29: error: 'KEY_ROTATE_LOCK_TOGGLE' undeclared (first use in this function); did you mean 'KEY_ATTENDANT_TOGGLE'?

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>
[Handel applied for rocko context]
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>