ibus: missing installed file w/ gtk2 PACKAGECONFIG
Source: meta-openembedded
MR: 297304
Type: Integration
Disposition: Merged from meta-openembedded
ChangeID: 6aab558e228a4134c1acfb41a415e2799845ae66
Description:

In case gtk2 PACKAGECONFIG is enabled, do_package task fails
with the following error:

ERROR: ibus-1.5.26-r0 do_package: QA Issue: ibus: Files/directories were installed but not shipped in any package:
  /usr/lib/gtk-2.0/2.10.0/immodules/im-ibus.so

This patch adds the missing folder to the FILES variable.

Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit c87c5d5614bf5d5255e031abe32ea681968a6d75)
Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>